
ARG INSTALL_ODOO_VERSION=17

# or odoo:17.0
# FROM mcr.microsoft.com/devcontainers/python:1-3.11-bullseye
# FROM odoo:${INSTALL_ODOO_VERSION}
FROM docker.io/bitnami/odoo:${INSTALL_ODOO_VERSION}

ENV PYTHONUNBUFFERED 1

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends wget netcat iputils-ping nano dos2unix git

# USER root
COPY poetry.lock pyproject.toml ./
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

# Copy my preferred .bashrc to /root/ so that it's automatically "sourced" when the container starts
COPY .bashrc /root/
